services:
  apiapp:
    build:
      context: ./api/
    networks:
     - redConexion
    ports:
      - 3001:3001

  dashboardapp:
    build:
      context: ./dashboard/
    networks:
     - redConexion
    ports:
      - 80:80

networks:
  redConexion:
    driver: bridge