services:
  apiapp:
    build:
      context: ./api/
    networks:
     - redConexion
    ports:
      - 3001:3001

  dashboardapp:
    build:
      context: ./dashboard/
    networks:
     - redConexion
    ports:
      - 80:80
  
  jenkins:
    image: jenkins/jenkins:lts
    ports: 
     - "8080:8080"
     - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  redConexion:
    driver: bridge