version: '3'
services:
  apiapp:
    container_name: APP_POLI_API
    build:
      context: ./api/
    networks:
      - redConexion
    ports:
      - 3000:3001

  dashboardapp:
    container_name: APP_POLI_DASHBOARD
    build:
      context: ./dashboard/
    networks:
      - redConexion
    ports:
      - 80:80

networks:
  redConexion:
    driver: bridge
